src/components/@common/Header/index.jsx
> - #10
> 공통 컴포넌트 헤더 ui
>왼쪽에 로고 부분은 임시로 주워서 업로드해 두었습니다!
> 로그인시에는 프로필 이미지기능 추후 추가
>비 로그인 시에는 로그인 페이지로 연결되게 해두었습니다.
=> [Feat] Header common component

src/components/@common/Header/index.jsx, src/components/BookCaroussel/BookCarrousel.jsx
> - #75 
> book Caroussel ui
> Header 부분에 Z-index 50으로 수정
> 버튼 말고 노란색 배경 Div에  지저분한 삼항연산자 식을 좀 간결하게 쓸 수 있는 방법이 있을까요..
=> [Feat] book Caroussel

src/App.jsx, src/pages/Challenge/ChallengePage.jsx
> - #20 
> 챌린지 설명 페이지 ui 구현
> App.jsx에 /challenge 경로 추가
=> [Feat] ChallengeDetailPage

src/pages/MyPage/MyPaymentListPage.jsx
> - #121
> MypaymentList 페이지를 지원님이 맡으신 마이페이지 스타일과 같게 수정하였습니다.
> 또한 Location 위치를 수정하였습니다.
=> Style: MypaymentList 페이지 gap, padding, Location 위치 수정

src/App.jsx
=> Bug: 불필요한 코드 삭제

src/App.jsx, src/pages/index.js
=> Refactor: PaymentComplete 코드 정리

src/components/BookCaroussel/BookCarrousel.jsx, src/pages/Challenge/ChallengePage.jsx, src/pages/Home/IndexPage.jsx
> - #127 
> 좌, 우 슬라이드 버튼 클릭시 3개씩 이동
=> [Feat] IndexPage, ChallengePage 슬라이드 기능 구현

src/components/AdminRecommendSpolier/index.jsx, src/pages/Admin/AdminBookCreatePage.jsx, src/pages/BookSpoiler/BookSpoilerPage.jsx, src/pages/MyPage/MyPaymentListPage.jsx, src/pages/Payment/PaymentPage.jsx
> - #103 
> admin 페이지에서 책 등록/수정 UI입니다.
> 또한 사소하게 스타일이 바뀌었습니다.
=> Feat: admin 책 등록 수정 UI

src/components/@common/Header/Header.jsx
=> [Feat] Header 간격변경

src/components/AdminRecommendSpoiler/index.jsx, src/pages/Admin/AdminBookCreatePage.jsx
> - #166 
> 공통 컴포넌트 사용
> 자동 줄바꿈 텍스트 수정 (width를 더 넓게)
>
=> Refactor: admin 도서 등록/수정 관련 코드수정

src/components/BookComment/index.jsx
> - #161 
> statusCard 변경될 때 scrollTop 되어서 페이지 상단으로 가기
=> Refactor: statusCard 변경될 때 scrollTop

src/pages/Admin/AdminCommentPage.jsx
=> [Feat] Admin 댓글관리 페이지

src/pages/Challenge/ChallengeActionPage.jsx
> - #169 
> 6일차 (완주)에서 챌린지완료 (댓글 작성 ) 후 미완료 > 완료가 되었을 때 큐레이터 스포일러도 6일차에 그대로 있어야 함
> 지금은 다시 1일차로 넘어가고 있는 부분 수정 완료
=> Refactor: ChallengeActionPage > 챌린지 완료 댓글 후 qurator spoiler 변화 수정

src/components/BookInfoCard/index.jsx
> - #168 
> 북카드 스타일 변경 (책 이미지 돌출)
=> Style: BookCard 스타일 변경

package-lock.json, package.json, src/components/BookInfoCard/BookCardLinkNone.jsx, src/components/BookInfoCard/Modal.jsx, src/components/BookInfoCard/index.jsx
> - #175 
> 북스포일러 페이지에서 외부링크 3개 초과 클릭시 로그인 창 모달 구현
=> Feat: BookCard 외부 링크 3개 초과 클릭시 모달창 구현

src/api/book/index.js, src/api/comment/index.js, src/api/common/index.js, src/api/keyword/index.js, src/components/BookComment/index.jsx, src/pages/BookSpoiler/BookSpoilerDetailPage.jsx, src/pages/Login/LoginPage.jsx, src/utils/RandomColor.js
> - #151 
> utils 폴더에 RandomColor.js 생성했습니다. 키워드 관련해서 조회하실 때 쓰시면 됩니다!
> api 폴더 > 카테고리 생성 후 기능 추가 
> 카카오톡 로그인
=> Feat: 카카오톡, BookSpoilerDetail > api 폴더 및 기능, 랜덤 컬러 util 파일

src/components/@common/Header/Header.jsx
> - #178 
> a태그 -> span태그로 변경
> href -> Link태그로 변경
> 챌린지 부분 cursor pointer추가
=> [Refactor] Header 컴포넌트

.env
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> remove .env file from git repo

src/components/BookComment/BookComment.jsx, src/components/BookComment/ChallengeComment.jsx, src/components/BookComment/ChallengeDeleteComment.jsx, src/components/BookComment/ChallengeEditComment.jsx, src/components/ChallengeSpoiler/index.jsx, src/components/ChallengeStatus/index.jsx, src/hooks/useFetch.js, src/pages/BookSpoiler/BookSpoilerDetailPage.jsx, src/pages/Challenge/ChallengeActionPage.jsx
> - #190 
>  ChallengeActionPage > BookComment 분리, 수정
=> Feat: ChallengeActionPage > BookComment 분리, 수정

src/App.jsx, src/components/@common/Header/Header.jsx, src/pages/Challenge/ChallengeActionPage.jsx
> - #201 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> Refactor: 경로수정, 헤더 마이페이지 메뉴 추가 (로그인 한 경우)

src/components/BookCaroussel/BookCarrousel.jsx
> - #204 
> 챌린지용 스포일러 더보기 버튼 클릭시 로그인 상태면 구매로 이동 아닐경우 로그인으로 이동
> use Fetch 추가 및 주석처리
>
=> 204 feat bookcaroussel

src/components/BookInfoCard/index.jsx
> #209 
> 북스포일러 상세페이지로 통하는 링크를 수정하였습니다.
>
=> Refactor: 북스포일러 상세페이지로 통하는 링크 주소 수정

src/components/@common/Input/index.jsx, src/pages/MyPage/MyInfoPage.jsx
> - #213 
> Input placeholder -> value로 변경
> api 추가 후 주석 처리
>
=> [Feat] 회원정보 페이지 api연동 주석처리

src/components/BookCaroussel/BookCarrousel.jsx, src/pages/BookSpoiler/BookSpoilerPage.jsx, src/pages/Home/IndexPage.jsx
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> Feat: 배포 수정1
